version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cursos
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  db:
    driver: local
